#!/bin/bash
#################################################################################
## Pre-Requisites: Your shell should already have AWS CLI installed and
## configured (aws config) with access keys already saved into ~/.aws/credentials
#################################################################################
## Begin User-Configurable Variables - change as necessary or as needed

## This is the directory where you want your vagrant instances to be created under
VAGRANT_DIR=/path/to/your/vagrant/directory

## 'ami-8c1be5f6' is default Amazon Linux AMI for US East (N. Virginia); change as you wish
AMI="ami-8c1be5f6"

## Amazon Linux AMI has 'ec2-user' as the login name; Ubuntu AMI uses 'ubuntu' as the login name
SSH_USER="ec2-user"

## This is the AWS instance type that the EC2 instance will be started as
INSTANCE_TYPE="t2.micro"

## You should create a Security Group in AWS Console with Port 22 and any additional ports you require open to access from your computer, and use this Group Name (not Group ID) below 
SECURITY_GROUPS="name_of_your_security_group_with_open_ssh_port"

## This is the "Key pair name" in AWS EC2 Console
KEYPAIR="aws_name_of_keypair"

## This is the path to the private key that you have downloaded when you initially created the AWS Key Pair 
SSH_PRIVATE_KEY="/path/to/your/.ssh/private_key.pem"

## End User-Configurable Variables
##################################

if [ n$1 == "n" ]; then
  echo
  echo "Error!"
  echo "  Syntax: `basename $0` instance_name"
  echo
  exit 1
fi
NEW_DIR=$1

cd $VAGRANT_DIR
if [ -d $NEW_DIR ]; then
  echo
  echo "Error: $VAGRANT_DIR/$NEW_DIR already exists!"
  echo
  exit 1
fi
mkdir $NEW_DIR
cd $NEW_DIR

cat <<EOF > Vagrantfile
Vagrant.configure("2") do |config|
  config.vm.box = "dummy"

  config.vm.provider :aws do |aws, override|
    aws.keypair_name = "$KEYPAIR"

    aws.ami = "$AMI"
    aws.instance_type = "$INSTANCE_TYPE"
    aws.security_groups = "$SECURITY_GROUPS"

    override.nfs.functional = false
    override.ssh.username = "$SSH_USER"
    override.ssh.private_key_path = "$SSH_PRIVATE_KEY"
  end
end
EOF

echo
echo "Created new EC2 Instance in $VAGRANT_DIR/$NEW_DIR"
echo "Run 'vagrant up' in above directory to start the instance"
echo
exit 0
